### PR TITLE
Browsing / editing branch content in the Wiki plugin does not work

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by gashcrumb** [comment]
This works great!  Am testing it on minikube and I can see that the URL parameters to fetch the file are correct, in my case the branch name used is `foobar`, however the file returned appears to be from `master`, at least it doesn't have the changes I made to it on the `foobar` branch.

Also the history button results in an error from forge, which I'll report to fabric8io/fabric8-forge, wonder if the returned file being from the wrong branch is also a forge issue.  @astefanutti did this work for you locally?  Thanks!

**Comment by astefanutti** [comment]
@gashcrumb I get the correct file content when I switch branches. I have a markdown file with a change on a separate branch and I can see the content change. I run `fabric8/fabric8-forge:2.2.211` image on my local OpenShift VM. Same for the history button, I can see the commit logs being displayed correctly. Maybe something to do with the version of `fabric8-forge` as well.

**Comment by gashcrumb** [comment]
Hmm, yeah, could also be one of the proxies in the way so very well could be specific to running on minikube.  I think this is worth merging, great work!

**Comment by astefanutti** [comment]
You're right, that may be an issue with the service proxying for external client. One way to find out is to execute (changing the OAuth header and the resource path): `curl -k --header "Authorization:Bearer PAMRYZRoGQKHLulnoELJiaVmxcGWQnqw3kftdoLvNLU" https://172.28.128.4:8443/api/v1/proxy/namespaces/default/services/fabric8-forge:80/api/forge/repos/project/default/profiles/content/profiles/example/camel/twitter.profile/camel-twitter-diagram.png?secret=gogs-https-admin&secretNamespace=user-secrets-source-admin&kubeUserName=admin`.

**Pull request merged**
