### PR TITLE
upgrade versions - thanks to @malagant

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by malagant** [comment]
Great to see that awesome quick PR :)
I forked the console and also got the trouble with bower update in circle-ci. I needed to choose what libs should be used for several dependencies. At the end my build worked. https://circleci.com/gh/malagant/fabric8-console/7

**Comment by jstrachan** [comment]
@malagant awesome! wanna just submit a PR from your changes and I can close this one?

**Comment by malagant** [comment]
Done :)

**Comment by jstrachan** [comment]
@malagant thanks! :)

**Pull request closed without merging**
