### PR TITLE
Updated to new bower dependencies to get rid of url trouble with ingresses

### PR DESCRIPTION
**Pull request by malagant**

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[merge]

**Comment by mycheng** [comment]
why is not realease now?

**Comment by jstrachan** [comment]
we're just about to release the new 4.x of fabric8 in the next couple of days hopefully; just finishing testing

**Comment by mycheng** [comment]
thx,  wait and expectantly

**Pull request merged**
